name: FixLag
version: 3.0
main: io.github.Earth1283.fixLag.FixLag
api-version: 1.19
author: Earth1283
description: Fixlag just got a major refactor/rework. Please report any bugs to the github issue thread
commands:
  fixlag:
    description: Fix lag on the server by cleaning up entities. Configure in config.yml
    usage: /fixlag
  stats:
    description: Show server stats.
    usage: /stats
permissions:
  fixlag.use:
    description: Allows the player to use the /fixlag command
    default: op
  stats.use:
    description: Allows the player to view server stats
    default: op