name: FixLag
version: 3.8.0
main: io.github.Earth1283.fixLag.FixLag
api-version: 1.17
author: Earth1283
description: Fixing lag without breaking farms!
permissions:
  fixlag.overload.exempt:
    description: Players with this permission will not trigger overload warnings.
    default: false
  fixlag.overload.notify:
    description: Players with this permission will receive overload notifications.
    default: op
  fixlag.command:
    description: Allows players to use the /fixlag command to manually clear entities.
    default: op
  fixlag.retrieve:
    description: Allows players to use the /fixlag retrieve command to open the deleted items GUI.
    default: op
  fixlag.gcinfo:
    description: Allows players to use the /gcinfo command to view GC information.
    default: op
  fixlag.serverinfo:
    description: Allows players to use the /serverinfo command to view server information.
    default: op
  fixlag.checkchunks:
    description: Allows players to use the /fixlag checkchunks command to analyze chunk entities.
    default: op
  fixlag.notify.distance:
    description: Allows players to receive notifications when view or simulation distance changes.
    default: op
commands:
  fixlag:
    description: Manually triggers the entity deletion.
    permission: fixlag.command
  gcinfo:
    description: Displays JVM memory and Garbage Collection information.
    permission: fixlag.gcinfo
  serverinfo:
    description: Displays server performance information (TPS, MSPT, RAM, CPU).
    permission: fixlag.serverinfo
