name: FixLag
version: 2.2.1
main: io.github.Earth1283.fixLag.FixLag
api-version: 1.19
author: Earth1283
description: Easily clear and mandage sources of lag in your server with minimal performance impact!
commands:
  fixlag:
    description: Manually remove entities
    usage: /fixlag
    permission: fixlag.command
permissions:
  fixlag.command:
    default: op
  fixlag.warning:
    default: op
